custom_environment_variables:
  CUSTOM_VAR: custom_value
go_command:
  args:
  - calc_subsets
  executable: ./mba/migration-bucket-accessor
migration:
  access_key: YOUR_ACCESS_KEY_HERE
  bucket: alice-sst-sdl-test
  cloud_provider: AWS
  log_level: DEBUG
  medium_tier_max_sstable_size_gb: 50
  medium_tier_worker_num_threads: 6
  optimize_packing_medium_subsets: false
  region: eu-west-1
  secret_key: YOUR_SECRET_KEY_HERE
  small_tier_max_sstable_size_gb: 10
  small_tier_thread_subset_max_size_floor_gb: 2
  small_tier_worker_num_threads: 4
  subset_calculation_label: mytieredcalc
  subset_calculation_strategy: tiered
s3:
  path_template: '{migration_id}/metadata/subsets/mytieredcalc/'
simulation:
  analysis:
    no_stragglers: false
    straggler_threshold: 20.0
    summary_only: false
  custom_args: []
  output:
    detailed_page_size: 30
    no_csv: false
    output_dir: simulation_outputs/{migration_id}
    output_name: migration_simulation
  worker_config:
    large_max_workers: 10
    large_threads: 1
    medium_max_workers: 6
    medium_threads: 4
    small_max_workers: 4
    small_threads: 6
